# Generated by Django 3.2.7 on 2021-09-09 02:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210908_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Enterprise',
        ),
    ]
